Users
dporth/clue-game pull request #10
Opened 2023-11-08 04:26 UTC by danielnashed

users endpoint updated with post, put, and delete

2023-11-08 16:53 UTC, mathewdenison commented
Looks good but need to fix code climate checks

2023-11-08 21:06 UTC, dporth requested changes
.DS_Store should not be committed

2023-11-08 21:10 UTC, dporth requested changes

2023-11-08 21:10 UTC, dporth commented on clue_game_backend/clue_game_api/urls.py
> +#from clue_game_api.users.views import createGame, joinGame, leaveGame, setCharacter
Commented out code should be removed

2023-11-08 21:10 UTC, dporth commented on clue_game_backend/clue_game_api/urls.py
> +    path("api/users/<int:id>/", UserView.as_view(), name="remove-user or set-character"),
user's id is not an int, it's an UUID. More likely need to declare the type str or something.

2023-11-08 21:10 UTC, dporth commented on clue_game_backend/clue_game_api/users/views.py
> +                return Response({'message': 'user created successfully'})
This response is not what was agreed upon in the api contract.

2023-11-08 21:10 UTC, dporth commented on clue_game_backend/clue_game_api/users/views.py
> +            return Response(serializer.data, status=200)
This response also is not what we agreed upon. For example, on of the fields returned by this response is `turn_status`. Our api contract specifies that this field is named `is_turn` in the response.

2023-11-08 21:10 UTC, dporth commented on clue_game_backend/clue_game_api/users/views.py
> +        return Response({'message': 'User left game session successfully.'})
This response also was not agreed upon in our api contract. The response should be an empty JSON.

2023-11-08 21:11 UTC, dporth requested changes

2023-11-08 21:11 UTC, dporth commented on clue_game_backend/clue_game_api/users/models.py
> +    #hallway = models.ForeignKey('hallway.Hallway', on_delete=models.CASCADE)
Please remove commented out code or put a TODO above it so we know the commented out code needs to be worked on still.

2023-11-09 00:01 UTC, mathewdenison commented on clue_game_backend/clue_game_api/users/views.py
> +            return Response(serializer.data, status=200)
Also generally speaking also 201 is returned if a new object is created vs 200 if the object already exists.

2023-11-09 00:02 UTC, mathewdenison commented on clue_game_backend/clue_game_api/users/views.py
> +        return Response({'message': 'User left game session successfully.'})
Should return a 204 for a deletion in general.

2023-11-10 00:11 UTC, danielnashed commented on clue_game_backend/clue_game_api/urls.py
> +#from clue_game_api.users.views import createGame, joinGame, leaveGame, setCharacter
resolved

2023-11-10 01:24 UTC, mathewdenison commented
Looks like DS_Store file is still committed. Check out this article on how to remove it from the group of files you are committing:

https://dev.to/morinoko/useful-git-commands-for-removing-accidentally-pushed-or-committed-files-2ld

2023-11-10 01:26 UTC, mathewdenison commented
Oh also code climate needs fixing before you can merge

2023-11-10 02:41 UTC, mathewdenison commented
Merge conflict fixed

2023-11-10 02:53 UTC, mathewdenison requested changes
Overall I think that the users changes are good but the edits to game files shouldn't be in the PR.

2023-11-10 02:53 UTC, mathewdenison commented on clue_game_backend/.gitignore
> +# DT store
Not sure if this is necessary. I'll defer to @dporth

2023-11-10 02:53 UTC, mathewdenison commented on clue_game_backend/api_contract.md
> +# Create User
Good call, not sure why we didn't think of this in the markdown file.

2023-11-10 02:53 UTC, mathewdenison commented on clue_game_backend/clue_game_api/game/apps.py
I think that this would delete the file in the repository, no? I don't think that's what we want here.

2023-11-10 02:53 UTC, mathewdenison commented on clue_game_backend/clue_game_api/game/migrations/0001_initial.py
I believe this migration would cause conflicts with the current master branch. We don't want to edit the migrations that are already established on the branch.

2023-11-10 02:53 UTC, mathewdenison commented on clue_game_backend/clue_game_api/users/admin.py
I don't think it's necessary to have an admin page for users.

2023-11-10 15:13 UTC, danielnashed commented on clue_game_backend/clue_game_api/game/migrations/0001_initial.py
so should I delete the 0001_initial.py files in my local repo before pushing you're saying?

2023-11-10 15:13 UTC, danielnashed commented on clue_game_backend/clue_game_api/game/apps.py
can you clarify more here?

2023-11-10 17:55 UTC, mathewdenison commented on clue_game_backend/clue_game_api/game/apps.py
In your merge request you explicitly deleted the apps.py in game, which when pushed up would cause that file to be deleted.

2023-11-10 17:56 UTC, mathewdenison commented on clue_game_backend/clue_game_api/game/migrations/0001_initial.py
I'd recommend just changing them to fit the model in master which would then reflect "no changes to the file" in your Pull Request

2023-11-10 17:59 UTC, mathewdenison commented on clue_game_backend/clue_game_api/game/apps.py
Basically when you pulled down master onto your branch yesterday, since master now has a game folder, since yours doesn't but your base is of master, it thinks you want to delete those files from master.

2023-11-13 01:13 UTC, closed without merging