Adding in game endpoints, build directly off master and migrated from…
dporth/clue-game pull request #12
Opened 2023-11-09 03:57 UTC by mathewdenison

Tested out and built off master. Please try on your machine before merging.

2023-11-09 18:01 UTC, dporth requested changes

2023-11-09 18:01 UTC, dporth commented on clue_game_backend/clue_game_api/game/migrations/0002_auto_20231109_0353.py
> +            name='isStarted',
thus far, we've used all lower case and underscores for database column names

2023-11-09 18:38 UTC, mathewdenison commented on clue_game_backend/clue_game_api/game/migrations/0002_auto_20231109_0353.py
> +            name='isStarted',
Seems unnecessary to fix at this point. We need these endpoints implemented for tonight's discussion and if this is the blocker to merging when I can't get to it until during/after our meeting then it's not worth fixing.

2023-11-10 00:11 UTC, dporth approved these changes

2023-11-10 00:12 UTC, hoppityhop approved these changes

2023-11-10 00:12 UTC, merged