Create initial game endpoints
dporth/clue-game pull request #9
Opened 2023-11-06 03:36 UTC by mathewdenison

2023-11-06 14:25 UTC, dporth commented on clue_game_backend/api_contract.md
> -			"session_id": "210730a4-6d46-11ee-b962-0242ac120002", // When "someone" creates a game, the BE is going to create a user for this person, this is their session id
This session id is actually needed. When a person creates a game, according to the flow we talked about, that person doesn't have a user created in our system yet. We create a user for that person when that person makes a request to create a game. The FE then needs to know the session id of this person.

2023-11-06 14:25 UTC, dporth commented on clue_game_backend/api_contract.md
> -			"session_id": "210730a4-6d46-11ee-b962-0242ac120002", // When "someone" creates a game, the BE is going to create a user for this person, this is their session id
You'll need to create a user in the POST game endpoint.

2023-11-06 14:25 UTC, dporth commented on clue_game_backend/clue_game_api/game/views.py
>          game = Game()
Where is game join code being set?

2023-11-06 14:27 UTC, dporth requested changes

2023-11-06 14:27 UTC, dporth commented on clue_game_backend/clue_game_api/game/views.py
>          game = Game()
Where is game join code being set?

2023-11-06 14:27 UTC, dporth commented on clue_game_backend/api_contract.md
>  			"join_code": "pawn123",
This session id is actually needed. When a person creates a game, according to the flow we talked about, that person doesn't have a user created in our system yet. We create a user for that person when that person makes a request to create a game. The FE then needs to know the session id of this person.

2023-11-06 14:27 UTC, dporth commented on clue_game_backend/api_contract.md
>  			"join_code": "pawn123",
You'll need to create a user in the POST game endpoint.

2023-11-06 16:04 UTC, mathewdenison commented on clue_game_backend/clue_game_api/game/views.py
>          game = Game()
It is being set in the models.py which is calling the create_random_join_code method. It is set as a default any time a new Game object is being created.

2023-11-06 16:05 UTC, mathewdenison commented on clue_game_backend/api_contract.md
>  			"join_code": "pawn123",
It is commented out until Daniel commits and merges his user endpoint. Don't want to add my own for sake of merge conflicts.

2023-11-06 16:11 UTC, mathewdenison commented on clue_game_backend/api_contract.md
>  			"join_code": "pawn123",
As for the session_id, that is also commented out for now, and will be implemented when we have the user endpoints created.

2023-11-06 16:13 UTC, mathewdenison commented on clue_game_backend/api_contract.md
>  			"join_code": "pawn123",
I'll add it back in as part of the api contract though. It was discussed at the meeting while you weren't there that we were supposedly planning to get rid of the session_id.

2023-11-06 16:19 UTC, dporth commented on clue_game_backend/clue_game_api/game/views.py
>          game = Game()
Nice

2023-11-06 16:20 UTC, dporth commented
Overall looks good, can you put in line code comments like "# TODO ..." to make known the things you are waiting on the user's endpoint to be done.

2023-11-06 16:24 UTC, mathewdenison commented
Yep I'll add that when I get home tonight along with changing back the apicontract file.

2023-11-08 02:11 UTC, mathewdenison commented
Updates made per requested changes. 
1. external_game_id changed to id
2. TODOs added
3. Removed change from api contracts file

2023-11-09 03:23 UTC, closed without merging